name: Build Linux gcc

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

concurrency:
  group: build-Linux-gcc-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Packages
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build

      # Install boost
      - name: Install boost
        uses: MarkusJx/install-boost@v2.1.0
        id: install-boost
        with:
          # Set the boost version (required)
          boost_version: 1.78.0
          # OPTIONAL: Specify a platform version
          platform_version: 20.04
          # OPTIONAL: Specify a toolset
          toolset: gcc

      # Configure cmake to build with Ninja Multi-Config
      - name: Configure
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_CXX_COMPILER=g++-10 -G "Ninja Multi-Config" -DCMAKE_CONFIGURATION_TYPES="Debug;Release" ..
        env:
          Boost_DIR: ${{ steps.install-boost.outputs.BOOST_ROOT }}/lib/cmake/Boost-1.78.0/
      # Build and test in debug mode
      - name: Build debug
        run: |
          cd build
          cmake --build . --config Debug
      - name: Test debug
        run: |
          cd build
          ctest -C Debug
      # Build and test in debug mode
      - name: Build release
        run: |
          cd build
          cmake --build . --config Release
      - name: Test release
        run: |
          cd build
          ctest -C Release
