name: Build Windows gcc

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: build-Windows-gcc-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Packages
        run: |
          choco install ninja
          ninja --version
          cmake --version

      # Install boost
      - name: Install boost
        uses: MarkusJx/install-boost@v2.1.0
        id: install-boost
        with:
          # Set the boost version (required)
          boost_version: 1.78.0
          # OPTIONAL: Specify a platform version
          platform_version: 2019
          # OPTIONAL: Specify a toolset
          toolset: mingw

      # Build and test in debug mode
      - name: Build debug
        run: |
          mkdir -p build-debug
          cd build-debug
          cmake -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -G "Ninja" -DCMAKE_BUILD_TYPE=Debug ..
          make
        env:
          Boost_DIR: ${{ steps.install-boost.outputs.BOOST_ROOT }}\stage\lib\cmake\Boost-1.78.0\
      - name: Test debug
        run: |
          cd build-debug
          make test
            # Build PDAAAL
      # Build and test in release mode
      - name: Build release
        run: |
          mkdir -p build-release
          cd build-release
          cmake -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -G "Ninja" -DCMAKE_BUILD_TYPE=Release ..
          make
        env:
          Boost_DIR: ${{ steps.install-boost.outputs.BOOST_ROOT }}\stage\lib\cmake\Boost-1.78.0\
      - name: Test release
        run: |
          cd build-release
          make test
