name: Build MacOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

concurrency:
  group: build-MacOS-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      # Install boost
      - name: Install boost
        run: |
          brew install boost ninja

      # Configure cmake to build with Ninja Multi-Config
      - name: Configure
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_CXX_COMPILER=clang++ -G "Ninja Multi-Config" -DCMAKE_CONFIGURATION_TYPES="Debug;Release" ..

      # Build and test in debug mode
      - name: Build debug
        run: |
          cd build
          cmake --build . --config Debug
      - name: Test debug
        run: |
          cd build
          ctest -C Debug
      # Build and test in debug mode
      - name: Build release
        run: |
          cd build
          cmake --build . --config Release
      - name: Test release
        run: |
          cd build
